name: "Wiz Security Scanner"
description: Integrates wiz security scanning for infrastructure-as-code and docker images
author: https://github.com/blstrco, https://github.com/buildkite-plugins
public: true
requirements:
  - docker
configuration:
  properties:
    api-secret-env:
      type: string
    file-path:
      type: string
    image-address:
      type: string
    parameter-files:
      type: string
    path:
      type: string
    scan-type:
      type: string
      enum:
        - docker
        - iac
        - terraform-files
        - terraform-plan
  required:
    - scan-type
  additionalProperties: false
